<a href="https://colab.research.google.com/github/eqbic/OSMI/blob/main/DataScience/ESA4/101numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1:** Import numpy as np

In [2]:
import numpy as np

**2:** How to create a 1D array


In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**3:** How to create a boolean array

In [5]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

**4:** How to extract items that satisfy a given condition from 1D **array**

In [6]:
arr = np.arange(10)
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

**5:** How to replace items that satisfy a condition with another value in numpy array

In [9]:
arr = np.arange(10)
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**6:** How to replace items that satisfy a condition without affecting the original array

In [10]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**13:** How to get the positions where elements of two arrays match

In [11]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

**14:** How to extract all numbers between a given range from a numpy array

In [18]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >=5) & (a <= 10))
a[index]

array([ 6,  9, 10])

**15:** How to make a python function that handles scalars to work on *numpy* array

In [19]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

**23:** How to limit the number of items printed in output of numpy array

In [20]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a


array([ 0,  1,  2, ..., 12, 13, 14])

**24:** How to print the full numpy array without truncating

In [26]:
import sys
np.set_printoptions(threshold=6)
a = np.arange(15)

np.set_printoptions(threshold=sys.maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])