<a href="https://colab.research.google.com/github/eqbic/OSMI/blob/main/DataScience/ESA4/101numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1:** Import numpy as np

In [2]:
import numpy as np

**2:** How to create a 1D array


In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**3:** How to create a boolean array

In [5]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

**4:** How to extract items that satisfy a given condition from 1D **array**

In [6]:
arr = np.arange(10)
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

**5:** How to replace items that satisfy a condition with another value in numpy array

In [9]:
arr = np.arange(10)
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**6:** How to replace items that satisfy a condition without affecting the original array

In [10]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])